version: '3.3'

services:
  big_data:
    container_name: big_data
    build: .
    restart: unless-stopped
    ports:
      - '8501:8501'

# networks:
#    default:
#      external:
#        name: main
